### ISSUE TITLE
Investigate communication with rasa

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#13]
How to communicate between rasa and niceday SDK?

**Comment by svenvanderburg** [comment]
Nele mentioned: How are messages going to get passed from and to the chatbot. As mentioned in one of our previous calls, I use rasa webchat as frontend, and then have a file called socketChannel.py that creates a custom socket channel so that custom information from the frontend can be passed to the backend. Have you thought about how to create this connection yet?

**Comment by svenvanderburg** [comment]
I would propose that we start with using the very simple [RestInput](https://rasa.com/docs/rasa/connectors/your-own-website#restinput) channel. This is an endpoint at the rasa server (usually http://<host>:<port>/webhooks/rest/webhook) that is available by default. Our NiceDay client (i.e. component that communicates to niceday server using niceday SDK) can just send a POST request to the rasa server whenever a message from a user is received. The rasa server will then immediately respond with the chatbot response message.

If the chat with the virtual coach is too slow we can decide to use the [websocket channel](https://rasa.com/docs/rasa/connectors/your-own-website#websocket-channel).

If we need to expand the communication beyond what is provided by the standard REST endpoint we can create a [Custom Connector](https://rasa.com/docs/rasa/connectors/custom-connectors)

**Comment by svenvanderburg** [comment]
@nelealbers what do you think?

**Comment by nelealbers** [comment]
@svenvanderburg The nice thing about the custom connectors is that we can also send metadata such as the ID of the user. Such an ID we might need to query a database, for example. I am not sure if this is also possible with the RestInput channel?

**Comment by svenvanderburg** [comment]
That's a good point @nelealbers. For now we only need an ID I think, which we can already pass with the RestInput channel. If we need to send more we can start using a custom connector.
