### ISSUE TITLE
Investigate rasa deployment

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#14]
How do we deploy rasa? (within the scope of the rapid prototype)

@nelealbers:
Setting up a rasa system itself takes no time, making sure it is easily portable is another thing. Currently, I have my chatbot running on a google compute instance with Ubuntu and rasa x installed on it. All the components then run within containers on this server. So I can easily provide instructions on how to run the containers on such an Ubuntu-rasa x server, but I am not sure how to make things more portable beyond that. That would certainly take more time.

@svenvanderburg :
I think we should start with the simplest possible thing and make that portable, we will worry later about how to merge the very simple chatbot that is the outcome of this sprint with all the stuff that rasa-chatbot-gather-rl-data already does. Those components that run within containers are they all necessary for the scenario that we want to achieve in the Sprint? But even if we need them I am pretty sure that we can make this portable using docker & docker-compose and some developer instructions. We have a separate issue (low priority) for automating deployment to the cloud.

@nelealbers : 
That is a good point. For the components that we will need critically, installing rasa x itself and then just running it with a trained model is sufficient. Running rasa x then automatically creates the various docker containers needed for the chatbot. The remaining parts depend more on how we plan to create the interface between the chatbot and the rest, i.e. how are messages going to get passed from and to the chatbot.

@svenvanderburg : 
See #13 for discussions for interface between chatbot and the rest
We continue discussion on deployment (within scope of the rapid prototype) here.

**Comment by svenvanderburg** [comment]
I propose the simplest possible design which should also be simple to deploy, I think we only need these components:
* open source rasa server (i.e. `rasa run`)
* open source rasa action endpoint server (i.e. `rasa run actions`)

Or @nelealbers would you say that using rasa x is simpler? Or adds features that we definitely need at this stage?

**Comment by nelealbers** [comment]
@svenvanderburg Using Rasa X does not make things harder, and it does make deploying on a server separate from the local laptop you build the agent on easier I think. So I currently use rasa core when I test my agent locally, but then I deployed my agent on a Google server via Rasa X and Docker containers.

**Comment by nelealbers** [comment]
Using Rasa X also means that you get a nice interface to look at the conversations your agent is having and what is happening during them.

**Comment by svenvanderburg** [comment]
Cool, thanks for elaborating. The rasa X interface is indeed really nice. If rasa X makes things easier in terms of deployment we should just use rasa X. I am a bit worried about it's restrictive license, see #15, so that might be the only downside then.
