### ISSUE TITLE
Investigate calling goalie-js directly from Python

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#17]
We use [goalie-js](https://github.com/senseobservationsystems/goalie-js) to communicate with the NiceDay server. Investigate whether we can interact with these javascript functions & classes directly from within our python application. The alternative would be to setup a javascript-based server that provides a REST-endpoint that we can than talk to from within python, but that is out of scope for this issue.

**Comment by raar1** [comment]
I was able to set this up using selenium (<https://pypi.org/project/selenium/>) and chrome running in headless (whole thing dockerized) to execute arbitrary javascript from python. However, it was a lot more convoluted than just writing the server in js and using node. I did also consider <https://github.com/timothycrosley/jiphy> but I worry that it will not be suitable for complex cases and it doesn't seem worth it.

I am closing the issue in favour of the pure JS server.
