### ISSUE TITLE
Check number of words for free-text answers in the future-self dialog

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#183]
As a user if I type less than 5 words as a response to a free-text question I want the virtual coach to ask me to rephrase my answer more elaborately. 

For example:
* VC: Leg uit, waarom zie jij jezelf als lichamelijk actief?
* User: Gewoon daarom
* VC: Zou je dat in meer woorden kunnen omschrijven?
* User: Ik ben gewoon een fitte jongen

**Comment by drcandacemakedamoore** [comment]
I can't assign myself, but I am looking at this issue (just as an FYI to others). Not sure how long it will take me, so if it is more urgent someone else can grab it.

**Comment by svenvanderburg** [comment]
Sounds good! I assigned it to you (not sure why you don't have that power...)

**Comment by drcandacemakedamoore** [comment]
OK, I did it inside the future self dialog for the question "Waroom have je deze werden gezoken voor roken". I'll now try to quickly duplicate the pattern wherever I see a free text pattern. It's on the drcandacemakedamoore/183- branch

**Comment by drcandacemakedamoore** [comment]
![IMG_20220213_180248_556](https://user-images.githubusercontent.com/31033601/153766470-0ae545de-b0a9-4136-8840-2d311725f8ea.jpg)
This thing is so unpredictable, I feel the need to show evidence.

**Comment by svenvanderburg** [comment]
@drcandacemakedamoore could you link the PRs that fixed this in the end? And then close the issue?

**Comment by drcandacemakedamoore** [comment]
[https://github.com/PerfectFit-project/virtual-coach-rasa/pull/17](url)
