### ISSUE TITLE
Investigate how to force virtual coach to slow down if uttering lots of messages sequentially

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#184]
A lot of text is thrown at the user at once. Investigate how we can set a sort of forced slow-down for the messages to send. Preferably this is at the level of rasa, but we can also set it at the level of the niceday-broker.

- [ ] Add your findings in this issue
- [ ] Create a follow-up issue for implementing this properly

**Comment by nelealbers** [comment]
See here for instance: https://forum.rasa.com/t/messenger-game-delay-bot-responses/43584/7.

**Comment by nelealbers** [comment]
Options:
- sleep in custom action in rasa: https://forum.rasa.com/t/messenger-game-delay-bot-responses/43584/7. Should to be implemented such that the custom action server can still take other requests in the meantime.
- on the side of the frontend (the broker for us?). Rasa webchat, for instance, allows custom delay: https://github.com/botfront/rasa-webchat. A discussion in this regard is here: https://forum.rasa.com/t/how-to-add-delay-between-chatbots-responses/28683/3.
- reminders in rasa: https://rasa.com/docs/rasa/reaching-out-to-user/#reminders. I.e., set a reminder to execute a next action a certain time period from now (e.g., 5 seconds).
