### ISSUE TITLE
Add test for future-self dialog

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#186]
Add a test story for the future-self dialog.

**Comment by drcandacemakedamoore** [comment]
This now has inadequate tests, but some tests on the actions (the appropriate ones are on 183 branch so everything can be PRs from there). There seems to be a problem with end-to-end testing in rasa.

**Comment by svenvanderburg** [comment]
@drcandacemakedamoore what is the status of this one? Can you link the PRs and close the issue if it's done?

**Comment by drcandacemakedamoore** [comment]
[https://github.com/PerfectFit-project/virtual-coach-rasa/pull/17](url)

The action is tested. I added extra code for a future fixture.
