### ISSUE TITLE
PA evaluation form stopped working

### ISSUE THREAD

**Issue by bscheltinga** [PerfectFit-project/virtual-coach-server#190]
After answering how the activity went, the bot goes to the fallback text instead of storing the answer and giving an custom reply.

Possible cause could be the upgrade to rasa 3 where you should add mapping conditions to slots:  https://rasa.com/docs/rasa/domain/#mapping-conditions

**Comment by nelealbers** [comment]
I tried to reproduce this bug but cannot. I answered with 3 and got a response with "jammer", and if I replied with 5 I got a response that it went well.

**Comment by svenvanderburg** [comment]
@bscheltinga If this is hard to fix, we could also choose to deprecate this dialog. It served it's purpose as a way of implementing functionality, but it will not be included in the final product.
