### ISSUE TITLE
Closed user answer datetime refreshes with populate_db.py

### ISSUE THREAD

**Issue by bscheltinga** [PerfectFit-project/virtual-coach-server#192]
I noticed that, after populating the db using helper/populate_db.py, the datetime values of the entries in closed_user_answers table refreshes. This is shown below:
![image](https://user-images.githubusercontent.com/45515920/152325294-d80fa4cf-ee6d-4843-bbad-f9038baeac5b.png)

I think this is undesired as this should be a fixed value. But probably is not a problem when we keep running the database? @svenvanderburg?

**Comment by bscheltinga** [comment]
I found that helper/populate_db.py does not load an existing database, but fills it manually, using: datetime=datetime.now())

**Comment by svenvanderburg** [comment]
@bscheltinga Yes this is true. I am not sure if this is a problem for testing any functionality right now? I suggest we change this whenever we need to test some functionality that depends on fixed datetime values.
