### ISSUE TITLE
success_save_calendar_plan_week

### ISSUE THREAD

**Issue by drcandacemakedamoore** [PerfectFit-project/virtual-coach-server#199]
When I am testing the above slot has really strange behaviors, it usually resets to whatever is in the last filled slot, which makes it change over the conversations many times, and contain data it should not.

**Comment by svenvanderburg** [comment]
We need to add an explicit condition for it since 3.0, see https://rasa.com/blog/slots-in-rasa-open-source-3-0/

**Comment by svenvanderburg** [comment]
@drcandacemakedamoore please create issues in `virtual-coach-issues` and not in the corresponding repo. I'll transfer the issue :)

**Comment by svenvanderburg** [comment]
Might be related to #190

**Comment by svenvanderburg** [comment]
This will probably fix it: https://github.com/PerfectFit-project/virtual-coach-rasa/pull/25/files Still need to test!
