### ISSUE TITLE
Look at Makedas report

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#202]
Look at @drcandacemakedamoore report: https://nlesc-my.sharepoint.com/:w:/g/personal/c_moore_esciencecenter_nl/ERtWbu5sZJRDu1GPzg8pAU8Brt5OuJKANitafM_V6f5OvQ?e=FlL4j0

Create follow-up issues for anything that needs further action.

**Comment by svenvanderburg** [comment]
Based on @drcandacemakedamoore report, I did the following things

updated https://github.com/PerfectFit-project/virtual-coach-issues/issues/197 with some options for disabling telemetry

### Merges versus rebase
_Merges versus rebases. I suspect this will bring strong opinions, and I am not a version control expert, so I really don’t have the right to authority. However, I see generally people are merging, and not rebasing. To cut complexity out of the history, I see no reason not to just rebase._  
I agree that rebasing is the best practice for version control. If the goal is to get a super clean version control history. I think for this project we don't really care about a clean history since we are a small team. Merging instead of rebasing is just a lot simpler, especially with our varying git-experience in the team. But I am also not an expert and I am not really used to rebasing, I only use it if I really have to (like the majority of the NLeSC).

### Repository size
_Repository size. It was suggested “maybe because you have a lot of model files on the different branches you created?” as the problem I have with size. Well, not really. The real problem is that they (models) are all in the history. Because there was not a linear history (see number 2), removing them now will be difficult. Going forward, I highly recommend making them an artifact_
For now we haven't encountered any problems with this. Moving forward we could have problems with this, but we can always delete old model files. I created https://github.com/PerfectFit-project/virtual-coach-issues/issues/239 for this.

### end-to-end testing
_No true end-to-end testing. I understand the way I use this terminology can be very confusing. By end-to-end I don’t mean just testing when the entire project is spun up. I think a better term may be integration tests. Not sure. I mean specifically inside Rasa, at present you can’t test a whole conversation including the actions all at once. Whenever actions will need to affect the flow of conversations, this is a problem. I don’t see an easy fix._
Solved with https://github.com/PerfectFit-project/virtual-coach-issues/issues/193

### Installation patch
_Installation patch is temporary. Rasa has very many dependencies and going forward it will be hard/take great effort to stay consistent. Again, forking, and throwing out unnecessary components is a potential fix._ 
Not sure what installation patch @drcandacemakedamoore you are referring to?

### Choosing OS for developers
_This is an infrastructure heavy project which really seems to work best on Linux for developers. I see you guys manage very well to do it on all kinds of platforms, but just a note you may want to warn people about if they have to choose an OS when they start working on it._  
I think development on Windows for Walter, Nele, and Bouke is going fine. I would say in general doing development on a Unix OS is nicer, but I am biased. I would not suggest someone to use an OS that they are not familiar with just for this project.

**Comment by svenvanderburg** [comment]
@wbaccinelli I would like you to also read through this and double check if my responses make sense.

**Comment by wbaccinelli** [comment]
@svenvanderburg I fully agree with the responses.

**Comment by drcandacemakedamoore** [comment]
Thank you for taking the time to read what I wrote. You don't have to take it so seriously...someone please close this already?

**Comment by svenvanderburg** [comment]
Haha, no I seriously appreciate the 'outsider' perspective. You get quite a bit of tunnel-vision when working on a project for a long time. But, OK, OK. I will close the issue ;)
