### ISSUE TITLE
Agent is triggered to ask start conversation on foreseen HRS's

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#21]
- At 9:00 AM we ask user whether the user foresees any High-Risk-Situations (HRS) for smoking, answer yes/no
- In case HRS is foreseen we say 'Hey, remember you can deal with cravings by watering your plants' (for now that is fine, later this should come from the database)
- In case of no HRS we say: 'Please be careful, cravings can always come unexpectedly'

- [ ] Add this story to rasa (add intents + utterances)
- [x] Come up with a way to trigger rasa to start this conversation. There's roughly 2 options: (1) From within rasa. (2) In a separate application that sends a POST request to rasa with a certain intent  from a user so that the conversation is started.
- [x] Implement the triggering (done in #41)
- [x] #112 
- [ ] Make sure everything works with docker-compose in the root, this includes enabling custom channel again, see: https://github.com/PerfectFit-project/virtual-coach-server/blob/3e3bf99610386b8803be28c8c377e87f42181559/Rasa_Bot/credentials.yml#L11
NB: In https://github.com/PerfectFit-project/virtual-coach-server/pull/131 we introduced a requirement for rasa server, so we need to define our own dockerfile (like we doe for actions server) to make this work.

[rasa tutorial](https://towardsdatascience.com/chatbots-made-easier-with-rasa-2-0-b999323cdde)

**Comment by CunliangGeng** [comment]
Rasa (the latest version is 2.6) does not have the repeat option to support periodic reminders. 
To have periodic reminders, there are at least two solutions:

**Solution 1:** 
Define a Rasa custom action to schedule a reminder using the `ReminderScheduled` event. When this event/reminder is executed, using `rules` to trigger the custom action again to schedule a new reminder, thus leading to an effect of periodic reminders.
**Cons:** All reminders will be gone when Rasa server has a shutdown or restart.

**Solution 2:**
Use cron job or other timer system to send Rasa [external event](https://rasa.com/docs/rasa/reaching-out-to-user/#external-events) to trigger specific intent.
**Potential problem:** The timer system should be scalable from a few jobs to millions of jobs and more.

The solution 1 has been implemented in the PR #38.

**Comment by svenvanderburg** [comment]
Blocked by #41

**Comment by svenvanderburg** [comment]
NB: please create the conversation in dutch

**Comment by svenvanderburg** [comment]
The scheduler has been implemented in #89, what remains is to finish the user story.
