### ISSUE TITLE
Create V2 software development planning

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#226]
See https://nlesc.sharepoint.com/:w:/s/team-flow/Ea_g6imfJulOvo0OJFw8m6cB3LwboDG1ReiJEIXwCkKRfQ?e=75uaLq for the first version.

**Comment by wbaccinelli** [comment]
New version [here](https://leidenuniv1.sharepoint.com/sites/TeamAio/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FTeamAio%2FShared%20Documents%2FGeneral&viewid=c0b07892%2D4a36%2D4ab0%2D8d81%2Df9ac52e34585)
