### ISSUE TITLE
Add slots content check in testing

### ISSUE THREAD

**Issue by wbaccinelli** [PerfectFit-project/virtual-coach-server#234]
Currently, the testing procedure doesn't allow to verify if the content of a slot has been correctly set. The check is indirectly performed by verifying the content of the responses produced by Rasa, where the slot is used. It would be useful to have the slots content verified per se.

**Comment by svenvanderburg** [comment]
We already do for unittests of the actions: https://github.com/PerfectFit-project/virtual-coach-rasa/blob/dd1a951fe3b9f0981b3ff4e19803dafdb0229568/Rasa_Bot/tests/test_actions.py#L18
