### ISSUE TITLE
Privacy/GDPR related issues

### ISSUE THREAD

**Issue by raar1** [PerfectFit-project/virtual-coach-server#235]
The PF app will process sensitive/confidential data (medical?) of its users. At the very least, it should be compliant with GDPR. As a result, there are several considerations and decisions to make:

- [ ] **Logs** Default logging on Heroku appears to go via the US, even if apps are running in the Euro region. We could audit our services so that we are sure user data is not leaked to logs (e.g. via a debug statement) but most likely we want to setup something e.g. <https://devcenter.heroku.com/articles/private-space-logging> or other loggin add-on
- [ ] **Isolation** If the isolation of our dynos from others running on Heroku is insufficient for PF, we may want to consider using [Private Spaces](https://devcenter.heroku.com/articles/private-spaces) or the even more locked down [Shield Private Spaces](https://devcenter.heroku.com/articles/shield-private-space). What do we actually require?
- [ ] ** Database ** We are using a managed postgres db. We have related concerns regarding privacy/compliance. There are many options on offer, so the best choice needs to be determined.

**Comment by raar1** [comment]
It appears we need private spaces at least, or we can't have secure communication between our dynos...
<https://blog.heroku.com/heroku_private_spaces_private_paas_delivered_as_a_service>

**Comment by wbaccinelli** [comment]
The discussion is ongoing with the experts of LUMC. The following steps are taken: 

- [Security Impact Assessment](https://nlesc.sharepoint.com/:x:/s/team-flow/EYnL9kdRXztBo1ztecDyivgBI8knbBHO17QU9Xun6xZq1Q?e=HoRp5H)
- Verification of the certificates available for DigitalOcean
- Verification of the compliance of NiceDay

**Comment by Wouter1** [comment]
Just my 2 cents.
I think in the netherlands we have to comply with NEN7510

**Comment by wbaccinelli** [comment]
Assessment performed by Security officers of LUMC. NiceDay and DigitalOcean compliant. Followup picked up by LUMC (system owner)
