### ISSUE TITLE
Design 'central mode'

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#242]
Relates to https://github.com/PerfectFit-project/virtual-coach-issues/issues/225

Design the central fallback mode

Whenever a dialog ends, the virtual coach makes it clear to the user that the coach now goes to 'central mode'. This mode can be a vey restricted keyword-based interface. Or it can be a relatively free chatbot. See more details in #225.

We will get input from the demo #230

**Comment by wbaccinelli** [comment]
After the discussion during the demo, we decided to implement a a restricted keyword-based interface. 
Even if a free-mode will not be implemented, critical keywords unrelated to the dialogs, but for which help has to be provided to the user (e.g., sick, depressed) will be detected. In this latter case, the VC will suggest the user to ask for help to his/her GP.
The starting and the ending of the dialogs will be made clear, to have the user always understanding the conversation context.

**Comment by svenvanderburg** [comment]
To help I will assume a central mode that has 2 keywords: 'first-aid kit' and 'I smoked'
## Separate rasa agents for 'dialog mode' and 'central mode'
We could have a separate rasa agent for 'dialog mode' and 'central mode', but I think this will only complicate things:
* 2 agents running probably running in their own containers, both need to be maintained
* Somehow the messaging channel (be it niceday or something else) needs to be routed to the correct agent, I think this is really not trivial. Probably you need a router that sits on top of the two agents and routes to the correct one based on an internal state. This state can be set by all of the other components to switch from central mode to dialog mode.

## A single rasa agent
We will have a distinction between:
* Dialogs that are triggered by external intents
* Dialogs that are triggered by keywords, they can be triggered from the 'central mode'

I suggest to use a custom regex-based intent classifier, see [gist](https://gist.github.com/svenvanderburg/b9fa7bff1317a09fb4c3e115bf2a618d), together with a fallback classifier.

* When a user types: 'first-aid kit', the intent is classified as 'request_first_aid_kit' and we trigger the first_aid_kit dialog. We use a rasa rule to make sure the keyword always triggers the right dialog.
* When a user types 'something else' or something misspelled like 'first 8 kit', the fallback classifier will kick in and the bot responds with 'You are in central mode, please use 'first-aid kit' or 'I smoked' bla bla bla'.

### But the fallback classifier will also kick in in dialogs and that is weird?
In theory, the fallback classifier could kick in in the middle of a dialog and say: 'You are in central mode, please use 'first-aid kit' or 'I smoked' blablabla'. That would be weird right?

Currently within the dialogs, we don't leave any freedom for free-text queries to the agent. We either use buttons, or validation of the answer, but we don't need any intent classification. So the fallback classifier will never be activated.

If at some point we do want more flexibility in the dialogs, we could use a slot to mark the state ({'dialog', 'central_mode'}) and based on that decide what the fallback utterance is.

## Buttons
If we have a messaging platform with buttons, we could just use one question with buttons ('first-aid kit' and 'I smoked') for the central mode...
