### ISSUE TITLE
Creation of the onboarding process

### ISSUE THREAD

**Issue by wbaccinelli** [PerfectFit-project/virtual-coach-server#248]
An automatic onboarding procedure has to be created to allow a new user to use PerfectFit. 
Assuming that an account has been created, the onboarding should include the following steps:
- Connection request has to be sent to the therapist account 
- Request has to be accepted though the therapist account
- A new entry has to be added to the DB

Blocked by #91

**Comment by svenvanderburg** [comment]
See also https://github.com/PerfectFit-project/virtual-coach-rasa/blob/main/onboarding/onboarding.py
