### ISSUE TITLE
Create preparation phase dialogs trigger

### ISSUE THREAD

**Issue by wbaccinelli** [PerfectFit-project/virtual-coach-server#249]
If the user is the preparation phase, the following dialogs have to be proposed to the user as described [here](https://leidenuniv1.sharepoint.com/:x:/r/sites/TeamAio/_layouts/15/Doc.aspx?sourcedoc=%7B30A1B8E4-E7EE-4BFD-A53E-8E95E69814D7%7D&file=2022.04.04_Perfect%20Fit%20app%20bible%20(Content%20overview%20and%20planning).xlsx&action=default&mobileredirect=true):
- Profile creation
- Medication talk
- Cold turkey
- Plan quit & start date
- Mental-contrasting (future-self-dialog)
- Goal-setting 

When the user connects, the intervention status of the user has to be checked. If the user is in the preparation phase, the not yet done dialogs have to be started. 

- [x] Create a placeholder story for each dialog
- [x] When a dialog is over, communicate it to the scheduler
- [x] In the scheduler, check what is the next dialog to be administered
- [x] Prompt the first not yet done dialog
- [x] Update the status of the intervention

**Comment by svenvanderburg** [comment]
First focus on 'profile creation'.
* Create a placeholder story, take your time to study rasa a bit
   - Train rasa
   - Test if everything still works, you can use https://github.com/PerfectFit-project/virtual-coach-main#for-developers
   - You can also try using `rasa shell` for quick testing of rasa in isolation
* Find out how to trigger the story, maybe you can use postman
  - https://github.com/PerfectFit-project/virtual-coach-rasa/tree/main/scheduler#how-to-manually-trigger-rasa
* Search for `EXTERNAL_trigger_ask_foreseen_hrs` in rasa:
   - https://github.com/PerfectFit-project/virtual-coach-rasa/blob/9e4715ad468c83238948e0926c806d39f1627191/Rasa_Bot/data/rules.yml#L29
   - https://github.com/PerfectFit-project/virtual-coach-rasa/blob/0b3de1c571f94b20e6ef572a260b5eb34817fec7/Rasa_Bot/data/stories.yml#L88
* In your placeholder story, make sure to write that you finished to intervention compoment to the database, see:
https://github.com/PerfectFit-project/virtual-coach-rasa/blob/9e4715ad468c83238948e0926c806d39f1627191/Rasa_Bot/actions/actions.py#L818
* Write a function that gets the right data from the database
   - inspiration from: https://github.com/PerfectFit-project/virtual-coach-rasa/blob/9e4715ad468c83238948e0926c806d39f1627191/Rasa_Bot/actions/actions.py#L782

**Comment by svenvanderburg** [comment]
When a user finishes a intervention component:
we write the date, name of component, whetther it was finished
trigger the next intervention component (send a signal to scheduler in some way)
then we pursue with the next one
