### ISSUE TITLE
Add unit test for future self repetition query

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/virtual-coach-server#259]
Add a unit test to test the query in the action ActionGetFutureSelfRepetitionFromDatabase in Rasa that should get the most recently stored smoker and mover words from the database.

**Comment by wbaccinelli** [comment]
AS the future self dialog is most probably going to change, we should evaluate whether to implement specific testing at this point.

**Comment by wbaccinelli** [comment]
Future self dialog has been transformed in a video. The issue is no more relevant.
