### ISSUE TITLE
Investigate niceday alternatives

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#262]
During last monthly academic partners meeting we discussed whether using the niceday app still makes sense. We decided it is not a good fit for our target audience. Our target audience is older people with a lower socio-economic status. 
They:
* Don’t want to sport (let alone run) according to a schedule (maybe they can be nudged into going for a walk once in a while)
* Don’t want to have long and complex conversations with a chatbot in an app on their phone

But we are creating that.

A lot of the features from niceday app are only confusing and we don't need them. 

We should investigate whether there is a good alternative (telegram or signal were mentioned during the discussion) that would give a more intuitive UX.

Things to look out for:
* privacy
* UX
* Can we still meet all our requirements?

**Comment by svenvanderburg** [comment]
## Relevant requirements:
1. **In-app trackers** Number of smoked cigarettes, mood, step count etcetera.
1. **File support** Be able to send and receive files such as images
1. **Quick reply support** Ability to provide user with buttons to click to give a quick reply to a question from the bot.
1. **Simple UX** A pleasant user experience for our target audience (older people with lower socio-economic-status). This means: very easy to use and understand.
1. **Can be integrated** The platform can be easily integrated within our existing architecture.

## Irrelevant requirements:
1. **In-app planner** An in-app calendar that can be used to plan activities, reminders for trackers etc. It is questionable if users of our target audience actually want to use such a thing or whether it just complicates things, so I leave it out of the equation. Of course if the planner would have a nice UX then it would actually be a nice addition.
2. **Sensor data** The sensor data will be measured using a separate app (google fit or fitbit). The sensor data will be requested from the associated API of this app/platform. This will all be handled by the backend, so we can just swap the 'frontend' without consequences.
3. **In-app profile** A user profile that users can edit in the app. For apps that do not support this we can create and update the user profile through interaction with the chatbot. Since none of the apps have exactly the profile that we want, we need to have a dialog for profile creation anyway.

### Niceday app
* ✅    In-app trackers
* ✅ 🟡  File-support. Supported from 1st of July onwards. Will take much more time to implement in our system than the platforms that are supported by rasa.
* ✅    Can be integrated (it already is)
* 🔴   Quick reply support
* 🔴   Simple UX
* 🔴  Slow with many messages

### Telegram
* ✅    File support. See [docs](https://rasa.com/docs/rasa/connectors/telegram/#supported-response-attachments)
* ✅    Quick reply support. See [docs](https://rasa.com/docs/rasa/connectors/telegram/#supported-response-attachments)
* ✅    Simple UX, most users are already familiar to whatsapp, which is very similar.
* ✅✅    Can be integrated. Using full telegram bot functionality for rasa is well documented: See [documentation for connecting to rasa](https://rasa.com/docs/rasa/connectors/telegram/)
* ✅ Seems free to use
* ✅ ✅ big community for bots
* 🔴    In-app trackers

### Whatsapp
* ✅ 🟡  File support. It is not documented very well though, but it is possible through [Twilio](https://rasa.com/docs/rasa/connectors/twilio/).
* ✅✅    Simple UX. Probably most people are already familiar with it. But a possible downside is is that the bot is just one of their contacts.
* ✅🟡    Can be integrated. See [rasa docs](https://rasa.com/docs/rasa/connectors/twilio/). You need to do it via Twilio.
* 🔴    In-app trackers
* 🔴 Additional costs: $0.0135 per message. Total costs: 0.0135 * 1000 messages per user * 500 users = $6700
* 🔴 Quick reply support.

### Facebook messenger
* ✅    File support. See [docs](https://rasa.com/docs/rasa/connectors/facebook-messenger#supported-response-attachments)
* ✅    Quick reply support. See [docs](https://rasa.com/docs/rasa/connectors/facebook-messenger#supported-response-attachments)
* ✅    Simple UX, probably some users are already familiar to it
* ✅✅    Can be integrated. Using full facebook messenger functionality for rasa is well documented: See [documentation for connecting to rasa](https://rasa.com/docs/rasa/connectors/facebook-messenger/)
* ✅ Seems free to use
* 🔴 You force to people to create a facebook account
* 🔴    In-app trackers

### Google Hangouts
* ✅ 🟡 File support. See [docs](https://developers.google.com/chat/api/reference/rest#rest-resource:-v1.spaces.messages.attachments). It is a bit more tricky than other platforms.
* ✅ 🟡  Quick reply support. A little bit more difficult because you cannot use the rasa built-in interface for this. Possible through 'cards'. See [docs](https://rasa.com/docs/rasa/connectors/hangouts/)
* ✅    Simple UX
* ✅   Can be integrated. A bit more difficult than facebook messenger or telegram
* ✅ Seems free to use
* 🔴    In-app trackers

### Signal
* 🔴 🔴 🔴 Doesn't really support chatbots, there are [unsupported workarounds](https://fabiobarbero.eu/posts/signalbot/)

### A few more alternatives that I did not really investigate
* Email
* Sms
* Regular phone (using speech instead of text)
* Slack
* RocketChat, Twilio (SaaS used to manage different communication channels in one platform)

## Privacy
Regarding privacy: The users of any messaging app are bound to the app's privacy regulations. They must apply to the European GDPR law. Of course we need to make sure that everything we do with those messages is GDPR-compliant. [This article](https://dev.to/imthedeveloper/gdpr-and-telegram-bots-26j6) gives some pointers, such as hashing the telegram user id. And the ability to delete all data for a specific person. But these things are not any different from using the niceday app.

## How difficult will it be to change to a different messaging platform?
Of course it takes a bit of time to transfer, but in return we probably get:
* out-of-the-box integration with rasa
* buttons (which saves a lot of time, because we get less complicated conversations)
* file-support will be much easier to implement and use

So bottom-line, we probably save time by switching to another platform.

## Risk
* Maybe at some point the messaging platform is going to charge for bots

**Comment by nelealbers** [comment]
@svenvanderburg Another alternative is Slack and apparently also RocketChat, which I have never heard of: https://rasa.com/docs/rasa/messaging-and-voice-channels/.

**Comment by svenvanderburg** [comment]
Todo:
* Investigate Google Hangouts
* Interact with some existing bots in most promising platforms

**Comment by svenvanderburg** [comment]
Slides: https://nlesc.sharepoint.com/:p:/s/team-flow/Ea8BL0mB-RpBooEyEQgM_J8BwjQN1IAltYppR6sTEJhleg?e=H4xF1y

**Comment by bscheltinga** [comment]
### RRD app
RRD has an app in the play store and app store (https://play.google.com/store/apps/details?id=nl.rrd.activitycoach&gl=NL) which is baded on modules that can be turned on/off for previous projects. An instruction video for a previous project (SmartWork) can be found here: [https://youtu.be/COu80u7OBRs](url)

✅ In-app trackers, need to be customized
🟡 File-support. Videos are included, but not in chat. It can be implemented in chat.
🟡 Need to check how the back-end can be integrated. RRD indicated they are willing to expaned their app.
✅ Everything can be in one single app. Also the sensor data collector can be integrated.
✅ There is button support
🟡 Simple UX: comparable to NiceDay, but only relevant modules can be selected
🔴 Use is probably costly as the app needs to be tailored for Perfect Fit.
✅ Educational modules can be included: for example, as done for PA exercises in https://youtu.be/COu80u7OBRs?t=441

Currently, file-support is not supported in chat, but it might be redundant as files are supported in other modules within the app.

Note that RRD will develop an app (based on the framework they have), so this goes together with costs. The nice thing is that it is possible to customize it exactly to our wishes.
