### ISSUE TITLE
Implement 'central mode'

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#266]
Implement a restricted keyword-based interface based on the design in #242

**Comment by nelealbers** [comment]
Options:
- Have a set of keyword-based intents that the keyword classifier is supposed to pick up. Need to ignore these intents in places where they could unintentionally be triggered (e.g., free-text responses in future self dialog). But you can set to-be-ignored intents in forms, for example.
- Use the rasa pipeline component Sven mentioned: https://gist.github.com/svenvanderburg/b9fa7bff1317a09fb4c3e115bf2a618d. Important then is that we need a keyword that triggers this, e.g., "Menu" or "Option" or "Start"

**Comment by nelealbers** [comment]
I think for the fixed things (e.g., get first aid kit), we can use the keyword-based intents.

For emergency keywords unrelated to fixed things, we can use the pipeline component Sven mentioned to detect words such as "depressed" or "sick" and then direct people to a GP.

**Comment by nelealbers** [comment]
Thoughts for implementing the emergency keyword part:
- The custom component from Sven works with specific starting words. We do not have those.
- Need to think about which exact emergency keywords we use and in which situations. Probably only want them in central mode. 
- What are the words we want to do something with? And could these words also appear in other contexts where we do not want to treat them like an emergency?
