### ISSUE TITLE
Investigate EU-based messaging platforms

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#270]
Follow-up from https://github.com/PerfectFit-project/virtual-coach-issues/issues/262, we should investigate also EU-based messaging platforms. They would possibly be more GDPR-compliant compared to Telegram or Whatsapp.

**Comment by svenvanderburg** [comment]
@bscheltinga had a good suggestion

**Comment by wbaccinelli** [comment]
A possible alternative is to have an app by RRD containing both the chat and the trackers. The compatibility with the requirements listed in #262 should be investigated

**Comment by bscheltinga** [comment]
I did an update in https://github.com/PerfectFit-project/virtual-coach-issues/issues/262

**Comment by bscheltinga** [comment]
Updated #262 

In short: there is button support in the chat. No file support.
