### ISSUE TITLE
Share_and_create_graphs

### ISSUE THREAD

**Issue by wbaccinelli** [PerfectFit-project/virtual-coach-server#288]
Ideally, we would like to give feedbacks to the users on their behaviours through graphical representations. A way to do that would be to create the graphs using the collected data (e.g., plotly), save the image and share it in the chat.
We need to investigate if this is possible or not.

**Comment by wbaccinelli** [comment]
In [this issue](https://github.com/PerfectFit-project/virtual-coach-issues/issues/285) the functionality to share local files has been implemented. 
With standard python graphic libraries it is possible to save graphs as images.
We need to investigate how to create the graphs as designed in the [relapse dialog](https://teams.microsoft.com/_#/xlsx/viewer/aggregatefiles/https:~2F~2Fleidenuniv1.sharepoint.com~2Fsites~2FTeamAio~2FShared%2520Documents~2FGeneral~2FContent%2520folder~2FVirtual%2520Coach%2520Dialogs%2520and%2520Resources~2FC1%2520Dialogs~2FC1.19%2520Dialog%2520Relapse.xlsx?baseUrl=https:~2F~2Fleidenuniv1.sharepoint.com~2Fsites~2FTeamAio&fileId=76ac2bb1-6924-4e86-bb9f-c70e8266d78c&ctx=aggregate&viewerAction=view)

**Comment by BendikC** [comment]
For the next sprint:
- [x] Query the database for the relevant data. This will be done by joining the tables 'dialog_closed_answers' with 'closed_answers' on 'closed_answers_id', then subsequently selecting all entries with the corresponding user id, and finally selecting the correct question_id. Pseudo: SELECT question_id, answer_value FROM closed_answers JOIN dialog_closed_answers ON closed_answers_id WHERE user_id=user_id AND question_id=question_id
- [x] Draw the graph, this will be done in plotly, ideally a helper function will be made to draw graphs in the future and to reduce code duplication
- [x] Find out where to call the functions in the story and what data to include. In the excel sheet the barchart calls can be found on lines 67, 107 and 174 respectively. The titles and descriptions can also be seen there. 
- [x] Save the graph and actually send it out to the user, this has been mostly implemented already so it only requires a few calls of methods that exist, but the file path is hardcoded currently so maybe adding a slot to make this variable is also required eventually
