### ISSUE TITLE
Plan Calendar Event from Rasa Conversation

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/virtual-coach-server#29]
Depends on #11 .

- [ ] in actions/actions.py, fill in the placeholder function for adding the user's plan to his/her calendar.
- [ ] Afterwards, the custom action Docker image (gbna4/perfect_fit_prototype_actions) needs to be rebuilt and pushed to Dockerhub. The Dockerfile for this is in the Rasa_Bot-folder.

**Comment by svenvanderburg** [comment]
Will be fixed with #11
