### ISSUE TITLE
Implement Dialog Relapse

### ISSUE THREAD

**Issue by wbaccinelli** [PerfectFit-project/virtual-coach-server#291]
Implement C1.19 Dialog Relapse as described [here](https://teams.microsoft.com/_#/xlsx/viewer/aggregatefiles/https:~2F~2Fleidenuniv1.sharepoint.com~2Fsites~2FTeamAio~2FShared%2520Documents~2FGeneral~2FContent%2520folder~2FVirtual%2520Coach%2520Dialogs%2520and%2520Resources~2FC1%2520Dialogs~2FC1.19%2520Dialog%2520Relapse.xlsx?baseUrl=https:~2F~2Fleidenuniv1.sharepoint.com~2Fsites~2FTeamAio&fileId=76ac2bb1-6924-4e86-bb9f-c70e8266d78c&ctx=aggregate&viewerAction=view).

**Comment by BendikC** [comment]
@bscheltinga in branch 253 I have made new files for the relapse dialog so in order to avoid conflicts it would be nice if you could pull these changes into your own branch and implement your dialogs in there. I also spoke to Kristell about what happens after the dialog is ended. If any of the relapse phase branches are triggered during the execution phase we would want to return back to the component that we were in. Not sure whether this is up to me or you to implement but this can be discussed tomorrow.

**Comment by bscheltinga** [comment]
So as the dialogs get more comprehensive and complex, we need to prevent duplicates in utterances and checkpoints. As discussed with @BendikC and @wbaccinelli we decided on a few naming conventions and structuring the dialog.

For **checkpoints**, it should be: <dialog_name>\_<checkpoint_name>, e.g. relapse_dialogs_pa_parent. For **utterances**, we can use the same convention, thus: utter_<dialog_name>_<utter_name>, e.g. utter_relapse_dialogs_smoke_crave_1.

Furthermore, as dialogs get lengthy, we should add some structure to the utterances. Numbering in order of emerging in the conversation is a solution. Thus, utter_relapse_dialogs_smoke_crave_2 will follow after utter_relapse_dialogs_smoke_crave_1. 

Additionally, for structure it will help to number the stories based on the tree diagram. Each level will have a number to move **deeper** into the tree, referred to as level in the image below. Besides, we have a sub-level, referring to the exact leaf in the  current level. It is illustrated below:

![image](https://user-images.githubusercontent.com/45515920/194865882-78a63fde-bd51-45ec-b6d8-82c8ee42281f.png)

**Comment by bscheltinga** [comment]
@BendikC @wbaccinelli 
So I just tested the latest version, as pushed on https://github.com/PerfectFit-project/virtual-coach-rasa/tree/relapse_dialog

First I experienced that I had to comment out all the utter_smoke_lapse_x utterances to be able to train the model, otherwise it was just ignoring the domain_relapse_dialogs.yml file. After commenting it out, it works with the first form (two_options_form). After the form, I'll get into the fallback mode: "Sorry, ik begrijp (nog) niet wat je bedoelt, kun je me het op een andere manier duidelijk maken?". I checked with a debug utter, that the form is filled as it should. But after the form, it seem to fail. 

@BendikC maybe you can have a fresh look?

**Comment by wbaccinelli** [comment]
@bscheltinga @BendikC 
After a long exploration of the issue, I found out that at the form activation time, rasa runs the default action action_extract_slots, that gets the last intent of the user and tries to fill the required slot. In our case, the latest intent was the previous response of the user, so the slot was automatically extracted and validated, and the stories went on.
I tried to find a clean built-in solution but I could not. So I implemented the the following workaround:

# Slots with custom mappings
We can set the slots required by the form to have a custom mapping and an associated action that runs when the slot is to be filled in:

```
  crave_lapse_relapse:
    type: categorical
    values:
      - 1
      - 2
      - 3
    influence_conversation: true
    mappings:
      - type: custom
        action: custom_crave_lapse_relapse
        conditions:
          - active_loop: crave_lapse_relapse_form
```

The custom action has to check if the slot is filled at the form activation (before the user input), and to avoid that:

```
class CustomCraveLapseRelapse(Action):
    """Check if the slot has been set at the form activation"""

    def name(self):
        return "custom_crave_lapse_relapse"

    async def run(self, dispatcher, tracker, domain):
        if tracker.events[-1]['event'] == 'active_loop' and tracker.events[-1]['name'] == 'crave_lapse_relapse_form':
            return [SlotSet("crave_lapse_relapse", None)]
        else:
            return [SlotSet("crave_lapse_relapse", tracker.latest_message['text'])]
```
Finally, the regular validation_action can be used to verify the values and to decide what happens in case a wrong value has been input.

# Long list of utterances
I have also found out that rasa will raise an exception and will stop predicting actions in case the same action is run more than 10 times. This is the case of out long lists of utterances. We can override this setting using the `MAX_NUMBER_OF_PREDICTIONS`  environment variable. [I modified the Dockerfile to do this](https://github.com/PerfectFit-project/virtual-coach-rasa/blob/1b446fbece21721cf2cc3697ba1ca07c8a59fd5a/Rasa_Bot/Dockerfile#L5).

**Comment by wbaccinelli** [comment]
A more clean solution can be obtained by only using the validation action and check at the validation time which was the latest utterance of the bot. In case the last utterance is not the form activation utterance, then the validation should return a None value. 
An implementation of the function to search the latest utterance is [here](https://github.com/PerfectFit-project/virtual-coach-rasa/blob/b0763c5f28e67ec972954ca59183e5e4273ca915/Rasa_Bot/actions/helper.py#L45). An example on how to use it in the actions is [here](https://github.com/PerfectFit-project/virtual-coach-rasa/blob/b0763c5f28e67ec972954ca59183e5e4273ca915/Rasa_Bot/actions/actions_general_activity.py#L85).

Using this approach, the slot doesn't need to run custom actions, but just the regular validation action.
