### ISSUE TITLE
Implement 1.18 System-initiated lapse

### ISSUE THREAD

**Issue by wbaccinelli** [PerfectFit-project/virtual-coach-server#303]
Implement dialog as specified [here](https://leidenuniv1.sharepoint.com/:x:/r/sites/TeamAio/_layouts/15/Doc.aspx?sourcedoc=%7B1C135070-83AB-4508-82DC-8F1988D6B4E0%7D&file=C1.18%20Dialog2-HRS%20reflection.xlsx&action=default&mobileredirect=true)

**Comment by bscheltinga** [comment]
Relapse:
- Steps are < 8000
AND
- Failing goal three days in a row
- Failing goal 4 times in passed 5 days

**Comment by wbaccinelli** [comment]
> Relapse:
> 
> * Steps are < 8000
>   AND
> * Failing goal three days in a row
> * Failing goal 4 times in passed 5 days

@bscheltinga  Does this mean: 
Steps are < 8000 AND (Failing goal three days in a row OR Failing goal 4 times in passed 5 days) ?

Is the current day to be included in the 3 days in the past 5 days?

**Comment by bscheltinga** [comment]
@wbaccinelli yes, you are right with the brackets!

So let me phrase the second rule differently: failing the goal 4 days in 5 consecutive days. 
I think including the current day is tricky, cause you never know whether people plan to go for a late night walk.

**Comment by wbaccinelli** [comment]
@bscheltinga 8000 is a fixed value? Shouldn't it be the current steps goal?

**Comment by bscheltinga** [comment]
@wbaccinelli No! We decided that, if they fail their goal, but are stlil above 8000 steps, we do not see that as a lapse. This because they are sufficiently active according to their steps data.
