### ISSUE TITLE
Implement 1.17 Weekly reflection dialog

### ISSUE THREAD

**Issue by wbaccinelli** [PerfectFit-project/virtual-coach-server#317]
Implement the dialog as described [here](https://leidenuniv1.sharepoint.com/:x:/r/sites/TeamAio/_layouts/15/Doc.aspx?sourcedoc=%7B84443391-2359-4F44-9500-2B6A62209139%7D&file=FOR%20SPRINT%20FEB%208%20---%20C1.17%20Weekly%20reflection%20dialog.xlsx&action=default&mobileredirect=true)

Responsible: Kristell

**Comment by BendikC** [comment]
For next sprint:
- [ ] Refactor rules using or statements
- [ ] Test dialog flow and fix potential incorrect paths
- [ ] Figure out step counter retrieval, and fill slot accordingly
- [ ] Implement the additional custom actions marked as TODO related to information retrieval
- [ ] Figure out exiting mid-dialog and then coming back to same spot for certain parts
- [ ] Discuss the prepared questions with Kristell
