### ISSUE TITLE
Configure step count with dialogues

### ISSUE THREAD

**Issue by BendikC** [PerfectFit-project/virtual-coach-server#333]
We need to be able to access the step count for the weekly reflection dialog. We need to do two things for this:
- [ ] Store step count in the database (not sure if this is done already in another branch)
- [ ] Write a helper function in actions to retrieve the step count from the database

**Comment by bscheltinga** [comment]
Dialogs where step count is needed:
- [x] Weekly reflection dialog
- [x] Closing dialog
- [x] Goal setting dialog
- [x] Notifications

**Comment by bscheltinga** [comment]
I spotted: https://github.com/PerfectFit-project/virtual-coach-rasa/blob/a1879481a5f7a486d86a709853b16a5eaeb3df61/Rasa_Bot/actions/actions_weekly_reflection.py#L201

I do not understand why this is here...
