### ISSUE TITLE
Weekly reflection: type 'klaar' missing after equipment

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/virtual-coach-server#351]
In the weekly reflection dialog in row 190 in the excel-file, the user is supposed to type "klaar" to continue. This is not clear from the dialog, and rasa does not check if the user types "klaar" in the have_equipment form.

**Comment by wbaccinelli** [comment]
Sentence to be added:
Typ ‘klaar’ als je de vragen hebt beantwoordt’. Aternative formulations: ‘Laat me weten dat je de vragen hebt beantwoord door 'klaar' te typen.’ and ‘Wanneer je klaar bent met het beantwoorden van de vragen, typ dan 'klaar'

**Comment by wbaccinelli** [comment]
Validation added [here](https://github.com/PerfectFit-project/virtual-coach-rasa/commit/a546ee7067963b0a4169281bc0c6d196564c7194)
