### ISSUE TITLE
C1.16 General activity check bug

### ISSUE THREAD

**Issue by wbaccinelli** [PerfectFit-project/virtual-coach-server#362]
See behavior described in https://github.com/PerfectFit-project/testing-tickets/issues/8

**Comment by nelealbers** [comment]
There is also a typo in utter_general_activity_edit_2 (a "/").

**Comment by nelealbers** [comment]
And there is a bug in get_general_activities_options: there is a space missing before "wilt doen".

**Comment by wbaccinelli** [comment]
Options 2 and 4 available. They were not working because the available activities depend on the phase of the intervention.
