### ISSUE TITLE
Error in saving general activities to DB

### ISSUE THREAD

**Issue by wbaccinelli** [PerfectFit-project/virtual-coach-server#374]
Error log:
File "/app/actions/actions_general_activity.py", line 636, in run
root-rasa_actions-1    |     store_dialog_closed_answer_to_db(user_id, answer_value=effort + 1,
root-rasa_actions-1    | TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by nelealbers** [comment]
@wbaccinelli I tried to reproduce this but cannot. How did you get this error? This would only happen if the "persuasion_effort_slot" somehow is not set.

**Comment by wbaccinelli** [comment]
@nelealbers I was finally able to reproduce the error. The `persuasion_effort_slot` is set only in the branch  where `general_activity_first_execution` is false. So, in the first execution of the dialog the slot is empty.
