### ISSUE TITLE
Add sensor data error image

### ISSUE THREAD

**Issue by bscheltinga** [PerfectFit-project/virtual-coach-server#387]
The step goal overview in the weekly reflection cannot be displayed if no data is returned from the API (e.g. missing data). In this case, an error image should be displayed instead of the bar diagram.

https://github.com/PerfectFit-project/virtual-coach-rasa/blob/6476b119e6b790c4e5b73c0d29a9b78775616995/Rasa_Bot/actions/actions_weekly_reflection.py#L330C36-L330C86

**Comment by wbaccinelli** [comment]
See https://github.com/PerfectFit-project/virtual-coach-rasa/pull/134
