### ISSUE TITLE
Typing "doei" at end of profile creation dialog messes up messages received

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/virtual-coach-server#390]
After completing the profile creation dialog, I typed "doei" as response to the goodbye from the virtual coach. This led to a mix of messages about fall-back (as expected) and about doing another activity. This was confusing, because I could never respond to the fall-back menu.

See here: https://github.com/PerfectFit-project/testing-tickets/issues/19.

**Comment by wbaccinelli** [comment]
@nelealbers the next activity is triggered automatically few seconds after the completion of the profile creation dialog, as pert of the preparatory phase. So the new activity is not a consequence of the menu activated through 'doei'. but I agree that this can be a bit confusing

**Comment by nelealbers** [comment]
@wbaccinelli Yes I thought so. It is confusing though especially because the resulting messages are a mix of the fall-back messages and the new activity (they do not come in order, see the screenshots - the message about having completed an activity comes before the one about talking to somebody). 

And people typing "bye" or "doei" at the end of a dialog is something we definitely have to account for. I had this happen many times in my experiments even if participants were clearly told that the dialog is over and that they were not allowed to type anything anymore.

Maybe we can just block the virtual coach from responding during those seconds just like we do for the duration of the videos?

**Comment by wbaccinelli** [comment]
Yes, that's  a good idea and it should be easy to do!
