### ISSUE TITLE
Reformulate first coach utterance HRS dialog

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/virtual-coach-server#395]
See here: https://github.com/PerfectFit-project/testing-tickets/issues/29

Update:
After discussion, this would help fix this:
- [ ] The starting statement of the HRS dialog should work 1) when people type 'verder' to continue the dialog after it had expired in case of a relapse, 2) when people type 'help' and 3) when an uncompleted HRS dialog is automatically started. So the first statement should be reformulated to match all 3 cases. The current formulation says that the user asked for help, which is confusing in case 1 and case 3. Discuss with Eline what this new formulation should be.

**Comment by nelealbers** [comment]
@aversluis1 What would be a good new sentence here that works in all 3 cases mentioned above?

**Comment by aversluis1** [comment]
@nelealbers I have tried to keep it short, because if I elaborate - the text doesn't work for all three cases. 
My suggestion would be this: "Graag praat ik met je"

**Comment by nelealbers** [comment]
@aversluis1 Okay, so the dialog would then begin as follows:

Utterance 1 (changed from "Goed dat je om hulp vraagt!"): Graag praat ik met je.
Utterance 2: Ik ga je helpen.
Utterance 3: Gaat het om roken of lichamelijke beweging?

Does this sound good?

**Comment by aversluis1** [comment]
@nelealbers, yes, I think this is workable!
