### ISSUE TITLE
Rescheduling problems / execution problems

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#398]
A user is experiencing the following problems -- also see complete screenshot. 
> Instead of doing the message immediately, she wanted to reschedule to another moment. Sam asked when (four options), after trying to choose option 2 -- sam kept saying that he did not understand. So she could not continue. Also everytime she gave the response '2' and Sam didn't understand, the four prompts come (press help if ..., press exercise if ...) -- this was considered annoying. Maybe we can not show these four prompts when an individual is in a dialogue?

> Later Sam asked if she wanted to continue the dialogue (in between the four prompts). Nothing is said: but Sam later responds 'you finished a part of the preparation phase, good job'

>  A new dialogue is initiated by Sam, and the user wanted to do it now. The dialogue hower did not continue. She only got reminders that Sam hadn't heard from her in a while. Sam did not respond to her 'verder' reply. Currently, she can therefore not continue. She is stuck in the dialogue. 

![Gesprek (002)](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/9feb418c-2d78-448c-becd-7799b74bc370)

**Comment by emeijerperfectfit** [comment]
I think another user (Kimberley Lucas; e-mailadres probably something like that) had something similar. She wanted to do an exercise now, but nothing happened; see screenshot

![Screenshot_20230725-105202](https://github.com/PerfectFit-project/testing-tickets/assets/135458606/036e3f54-d6bf-4445-a00b-d0ccc9bf8b04)

**Comment by emeijerperfectfit** [comment]
And something similar that I encountered myself yesterday, when nothing happened when I typed verder

![Screenshot_20230724-172723](https://github.com/PerfectFit-project/testing-tickets/assets/135458606/fbbb0075-7792-48a0-8e58-e5929831d25e)

**Comment by wbaccinelli** [comment]
first issue related to delay and answering before the question has been delivered.

second issue to be investigated

**Comment by wbaccinelli** [comment]
@emeijerperfectfit when you have time, can you check if the coach is responding

**Comment by emeijerperfectfit** [comment]
> @emeijerperfectfit when you have time, can you check if the coach is responding

I’m not sure whether you meant the verder issue, but I just typed verder at 20.05 and did not get anything yet from the coach (it’s 20.16 now)

**Comment by emeijerperfectfit** [comment]
I also got some comments from other people testing the app about the verder thing. I think this might actually be the command that’s needed the most, as it’s very likely that people won’t be able to respond to the coach immediately (also when the messages are no longer sent during the night). I get the impression that it’s quite annoying for users to get the menu all the time. I thought a solution could be to stretch the time window in which people can continu with the dialog they were in, but the downside would be that they can’t e.g. use the help command then.
Would it be a solution to add an additional step when a dialog is not yet finished? In that case, the coach might not send the entire menu immediately, but first ask whether the user wants to continu with the dialog. If yes, continu with the unfinished dialog, if not, send the menu.

The additional step could like this:
Message 1: Hoi. Wil je verder gaan met het gesprek dat we hadden?
Message 2: Typ ‘1’ voor ja. Typ ‘2’ voor nee, als je iets anders wilt doen.
If 1, continu with dialog; if 2 send the menu such that the user can choose what to do

**Comment by wbaccinelli** [comment]
@emeijerperfectfit maybe it's easier if we have a short call

**Comment by emeijerperfectfit** [comment]
@wbaccinelli Now I have Sam neglecting the verder command in both of my accounts. I’ve include some screenshots from one of them (e.meijer@lumc.nl) from today. It also seems like the language model to detect commands is not functioning correctly, as it now starts the HRS dialog in respons to several commands including verder
![Screenshot_20230727-172328](https://github.com/PerfectFit-project/virtual-coach-issues/assets/135458606/2f6fa872-b0ee-4579-b327-b97597fc9000)
![Screenshot_20230727-172335](https://github.com/PerfectFit-project/virtual-coach-issues/assets/135458606/9d41a86a-919f-4112-8afa-27a406c54983)
![Screenshot_20230727-172316](https://github.com/PerfectFit-project/virtual-coach-issues/assets/135458606/8077a9fb-b484-4cec-850c-f8197788b84b)
![Screenshot_20230727-194043](https://github.com/PerfectFit-project/virtual-coach-issues/assets/135458606/081fb594-48dc-4f8a-b976-0b7dfc8e0f9a)

**Comment by wbaccinelli** [comment]
These screenshots might already help, thanks! 
In the last case, the verder command is actually working correctly. The last uncompleted dialog was the HRS dialog, so it started it again.
