### ISSUE TITLE
Choosing exercises dialogue

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#401]
I get an overview of the different exercises, but the name of the exercises does not fit in the sentence. See screenshot. 

- Would keep the 1 and 6 as it is
- 2nd one: 'advies over gezond eten' ( so it would become Typ 2 als je advies over gezond eten wilt)
- 3rd one: 'advies over beter slapen' 
- 4rd one: 'advies over het drinken van koffie en alcohol' 
- 5th one: 'advies over het omgaan met stress'

![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/d8cd4abf-451c-4dad-97b5-024b59ea2581)

**Comment by wbaccinelli** [comment]
@aversluis1 these are the titles of the exercises, we just report them here as they are. Changing them according to the context would be an overkill, but maybe we can put the title in quotation marks? What do you think?

**Comment by aversluis1** [comment]
@wbaccinelli, I think quotation marks might be the easiest solution indeed!
