### ISSUE TITLE
Ending 'movement advice'

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#402]
![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/1b868192-e540-4e3e-b877-ea366566b03f)

![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/08d5cb3c-d0db-4490-8cb9-b2cd1c049c92)
 
Aanpassen naar statement zou kunnen zijn 'Bedenk of jij het beweeg advies opvolgt.'

**Comment by wbaccinelli** [comment]
@aversluis1 no answer is expected here, this are just the instruction of the exercise. Let me know if the content has to be changed.

**Comment by aversluis1** [comment]
@wbaccinelli, please change because it is very confusing. You could change it to: Bedenk of jij het beweeg advies opvolgt.
Plus the emoticon that was used.

**Comment by nelealbers** [comment]
Already fixed here: https://github.com/PerfectFit-project/virtual-coach-db/pull/76.
