### ISSUE TITLE
End of dialog

### ISSUE THREAD

**Issue by emeijerperfectfit** [PerfectFit-project/virtual-coach-server#406]
Our advisory board member (and many others) found it confusing when you can and cannot send messages to the coach. He suggested to clearly end each dialog. Could we add the following message to every dialog that does not have a clear ending yet? I’ve made some variations in case that’s helpful (assuming that the start of the Sorry message can be replaced as I suggested in another issue)

- Dit was het voor nu. Ik sta voor je klaar, dus je kunt me op elk moment roepen door middel van de woorden.
- We zijn nu klaar. Ik help je graag, dus laat het weten als ik iets voor je kan betekenen!
- Dit gesprek is nu klaar, maar ik spreek je graag weer! Je kunt me op elk moment een bericht sturen, en dan laat ik weten wat we kunnen doen.

**Comment by wbaccinelli** [comment]
@emeijerperfectfit indeed. Can you also list the dialogs where we need to include this final sentence?

**Comment by emeijerperfectfit** [comment]
Sure! I can do that on August 15th, but if you need it sooner perhaps Anke can have a look at this
I by the way think the first message is better if we only use from ‘Dit was … elk moment’, so better to remove ‘door middel van de woorden’

**Comment by wbaccinelli** [comment]
@aversluis1 can you take a look at this?

**Comment by aversluis1** [comment]
@wbaccinelli, Yes I can. I will try to do so today (but might not manage). Otherwise it will be the beginning of next week. That okay?

**Comment by wbaccinelli** [comment]
@aversluis1 sounds good, thanks!

**Comment by emeijerperfectfit** [comment]
I think we also need a message ‘Dit is het einde van deze oefening’ at the end of each exercise

**Comment by aversluis1** [comment]
@wbaccinelli , I wanted to start with checking the ending of all the dialogs / exercises. Can you let me know where I can find the lastest version of these documents in Github? And would you like me to make changes to these files, or in a seperate file? What was is easiest for you to see what changes I made?

**Comment by wbaccinelli** [comment]
@aversluis1 The best would be to use the excel files with dialogs descriptions that you can find [here](https://leidenuniv1.sharepoint.com/sites/TeamAio/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x012000FF0493A502C07A42A0C04F2EC1F3A51D&id=%2Fsites%2FTeamAio%2FShared%20Documents%2FGeneral%2FContent%20folder%2FVirtual%20Coach%20Dialogs%20and%20Resources%2F1%20%2D%20C1%20Dialogs&viewid=c0b07892%2D4a36%2D4ab0%2D8d81%2Df9ac52e34585).

When a modification is made to a dialog, usually it is marked by writing 'new' in red in the last column, in the row where the changes occurred.

**Comment by aversluis1** [comment]
@wbaccinelli , for all dialogs I added clarification - when a dialog ends - that it is the end. Made changes in the following dialogs: C1.11 / C.1.9 / C1.17 / C1.20 / C1.8 / C1.13 / C1.14 / C1.19. 

Most of the times, I have made a small additions in existing lines. A couple of times, I had to add a new line to clarify that it was the end of the message for now. When I made changes to a line or added a line, I added NEW (in red) in coloumn D. 

@wbaccinelli, should these messages also be added to the resources? Or does that not make sense, as they are loaded into dialogs?

**Comment by aversluis1** [comment]
@wbaccinelli, just checked the individual resources and thought it would be better (also based on comments from a tester) to add one extra sentence that it is the end of the exercise (oefening). That sentence should not be a problem, if the exercise is shown in a dialogue. 

So .... all the exercises have 1 extra sentence. The extra sentence is highlighted in red. In a couple of exercises, I also changed the last sentence (as this was a question and we don't want to end the exercise with a question).

**Comment by wbaccinelli** [comment]
@aversluis1 thank you for doing this! Can you also tall me which resources have been modified?

**Comment by aversluis1** [comment]
all resources

**Comment by nelealbers** [comment]
Dialogs still need to be adapted.

**Comment by nelealbers** [comment]
@wbaccinelli I think 1.11 is not used anymore?

**Comment by wbaccinelli** [comment]
@nelealbers correct

**Comment by nelealbers** [comment]
@aversluis1 I just looked at 1.19. There are so many changes in red there that I do not know what all you changed.

I fixed line 294 and changed line 75 (utter_good_to_hear_2), line 141 (utter_good_to_hear_3), line 213 (utter_good_to_hear_2), line 285 (utter_good_to_hear_2). Is there anything else?

**Comment by aversluis1** [comment]
> @aversluis1 I just looked at 1.19. There are so many changes in red there that I do not know what all you changed.
> 
> I fixed line 294 and changed line 75 (utter_good_to_hear_2), line 141 (utter_good_to_hear_3), line 213 (utter_good_to_hear_2), line 285 (utter_good_to_hear_2). Is there anything else?

@nelealbers  I see that you closed the ticket, so does this mean you figured out what I changed? Or do you need further clarification?

**Comment by nelealbers** [comment]
@aversluis1 Yes, I think so. But if you could double-check, that would be great.

**Comment by aversluis1** [comment]
@nelealbers, just to clarify, you want me toch check/test it in the app or in the excel?

**Comment by nelealbers** [comment]
@aversluis1 I worked on the HRS dialog a bit more and I think I understood the excel file a bit better. I realized that you wrote small NEW statements in various places, rather than big ones. And I incorporated all those small ones. So no more checking needed.
