### ISSUE TITLE
HRS dialog - move possibility to stop at the beginning

### ISSUE THREAD

**Issue by wbaccinelli** [PerfectFit-project/virtual-coach-server#408]
In the smoke branch of the HRS dialog, the possibility to end the dialog is given to the user (Typ '4' als je per ongeluk 'help' hebt getypt en nu geen hulp nodig hebt). This should be moved to the first question of the dialog.

See also [this issue](https://github.com/PerfectFit-project/testing-tickets/issues/48)

See also [this](https://github.com/PerfectFit-project/testing-tickets/issues/53)

**Comment by wbaccinelli** [comment]
@aversluis1 I am moving the possibility to exit the relapse dialog at the beginning. The easiest thing to is is to incorporate this in the first question , but it will then be like this:

Gaat het om roken of lichamelijke beweging?

Typ '1' als je het gaat om roken. 🚬.
Typ '2' als het gaat om lichamelijke beweging. 🚶️
Typ '3' als je per ongeluk 'help' hebt getypt en nu geen hulp nodig hebt.

It sound a bit weird, can we rephrase it?

Also, if the user selects 3 and, thus, exits the dialog, it would be nice to have a last sentence to let him/her know that the dialog is over. Can you help me with this?

**Comment by aversluis1** [comment]
@wbaccinelli, I think the question sounds okay and doesn't need further rephrasing. 

IF the user exits then you could say: "Dit gesprek is nu klaar. Weet dat je mij altijd om hulp mag vragen. Ik ben er voor je!"

**Comment by wbaccinelli** [comment]
Great!
