### ISSUE TITLE
Look for scheduler framework to trigger Rasa to ask start conversation on foreseen HRS

### ISSUE THREAD

**Issue by CunliangGeng** [PerfectFit-project/virtual-coach-server#41]
To look for a scheduler framework or system as an external solution to trigger Rasa to ask start conversation on foreseen High-Risk-Situations (HRS) for smoking. See the details of requirements and discussions in the issue #21 .

- [x] investigate potential scheduler framework
- [x] deploy the scheduler and connect it to rasa
- [x] Update [the design](https://github.com/PerfectFit-project/virtual-coach-server/blob/main/docs/design.md) accordingly 

Ideas for schedulers:
- Celery (see [periodic tasks](https://docs.celeryproject.org/en/stable/userguide/periodic-tasks.html)
- Cronjob

**Comment by raar1** [comment]
This issue was addressed in PR #89

**Comment by svenvanderburg** [comment]
Scheduler will be added to design in #102
