### ISSUE TITLE
Unuseful activity called useful in general activity dialog

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/virtual-coach-server#413]
See here: https://github.com/PerfectFit-project/testing-tickets/issues/57.

**Comment by nelealbers** [comment]
Might be good to use conditional response variations to adapt the response to the rating, i.e., call the rating useful only when it is also high, not just if it is in the top 5.

**Comment by wbaccinelli** [comment]
see also https://github.com/PerfectFit-project/testing-tickets/issues/63

**Comment by nelealbers** [comment]
Maybe also want to change the utterance utter_general_activity_thanks_top_5_2 that currently goes like "Deze oefening heb je al eerder als nuttig beoordeeld. Je liet mij toen weten dat je het volgende geleerd hebt van de oefening: {activity_user_input}". Because if the activity was just the first activity, then this sentence that people found the activity useful earlier is also not true.
