### ISSUE TITLE
Add moderation to step PA relapse

### ISSUE THREAD

**Issue by bscheltinga** [PerfectFit-project/virtual-coach-server#416]
When designing the relapse rules for PA, one of the rules was:
- A goal is seen as met, if the total steps is >95% of the goal

Currently, this is not the case: a goal is seen as met if the total steps is >=100% of the goal. This form of moderation should be included.
- [x] Change get_step_goals_and_steps in connector
- [x] add the moderation factor of 0.95 to constants
- [x] Add (bijna) in sentence in reflection dialog:  "Je hebt op {step_goal_days} dagen je stappendoel (bijna) gehaald en ..."

**Comment by wbaccinelli** [comment]
see https://github.com/PerfectFit-project/virtual-coach-rasa/pull/134
