### ISSUE TITLE
Start goal setting dialog

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#417]
--> on 1/8 I got video c1.11 on future self, but didn't answer the question about whether video is clear. 
--> I didn't get a reminder to complete the question / dialog. 
--> but I also didn't get the next dialog about goal setting, which should have been planned on 2/8 (if I am correct). 

--> I now pressed 'verder' and got the dialog again. After I finished this, the dialogue about goal setting did start. 

I think the dialog about goal setting should come, whether or not the dialog scheduled after the video on the future self is completed.

**Comment by wbaccinelli** [comment]
@aversluis1 the future self dialog can be made non mandatory, shall we do that?.

The notification was planned exactly for the same moment in which another notification was scheduled. It should have been sent after a while anyway, but I don't know why this didn't happened.

**Comment by aversluis1** [comment]
Eline had the same problem, and also did not get the goal setting dialog. 
So I think it is smart to make the future self dialog non mandatory
