### ISSUE TITLE
HRS dialog

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#418]
Experiences eline: 

31/7 I thought I had finished the hrs dialog for smoking by indicating that I did not intend to ask for help (option 4), but then it asked me to continu with the conversation. See screenshot 

1/8 same thing happened
When I had finished the dialog I said dankjewel and the hrs dialog immediately started again, see screenshot 

I still see the 😭 in the hrs dialog, perhaps it's only replaced in one branch?

1/8 At night the hrs dialog started automatically even though I had finished it before and had not said anything to the coach since. See screenshot
![Screenshot_20230731-202503](https://github.com/PerfectFit-project/virtual-coach-issues/assets/118284434/b54ae805-ad27-4dcc-8876-a3f503c7e7a2)
![Screenshot_20230801-194339](https://github.com/PerfectFit-project/virtual-coach-issues/assets/118284434/946768e7-99ca-4cb2-9cf6-eded7f076ff2)
![Screenshot_20230802-185032](https://github.com/PerfectFit-project/virtual-coach-issues/assets/118284434/28f88573-0bcd-4386-9757-68eeb33be481)

**Comment by wbaccinelli** [comment]
solved [here](https://github.com/PerfectFit-project/virtual-coach-issues/issues/393)
