### ISSUE TITLE
Goal setting dialog

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#419]
in goal setting dialog, I have to write some stuff down and when I am finished i get the instruction to type 'klaar'. 
I type it, and then again i get the message that I should type klaar. 

This extra sentence should be deleted. 

![image](https://github.com/PerfectFit-project/virtual-coach-issues/assets/118284434/04a522ac-899d-4768-a1d7-ab59ace2604c)

**Comment by wbaccinelli** [comment]
This is the usual issue with sending the answer before the question. But, of course the last sentence at the end of the long message should be removed
