### ISSUE TITLE
Number of small issues 

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#421]
Tester: Eline

Goal setting dialog: after setting the quit date and the first klaar the messages came way to quickly 

Persuasion messages for exercises include "..". These dots should not be there. E.g. "De meeste mensen denken dat deze oefening zal helpen om ... vervelende gevoelens in je lichaam te zien als teken dat je goed bezig bent."

I set August 4th as my quit date but on that they I did not get a specific message indicating that it was my quit date (not sure whether this was programmed but would be good to send something), instead I immediately got the weekly reflection dialog and had to indicate how much I had smoked last week, which should be quite some cigarettes as I would have had only 1 day without smoking 
Additions Anke: I got a video about 'uitleg coachingsfase', but I agree that a message saying today is your quit day would be very beneficial'. 

Briefcase should also removed from the weekly reflection dialog, the part where people think about the week to come

4/8 I said dankjewel after the weekly reflection and then the hrs dialog started as I had apparently used my code word, see screenshot 
![Screenshot_20230804-142241](https://github.com/PerfectFit-project/virtual-coach-issues/assets/118284434/8c50d18f-dea7-49d7-aeb1-413171925f0f)

4/8 19.50 I texted some nonsense and got Sorry er is nu geen onvoltooide dialoog om af te maken, with the menu. Is that intended?

19.59 the coach stopped during the general activity dialog. I was on the campsite but I think my internet connection was ok. See screenshot 
![Screenshot_20230804-195033](https://github.com/PerfectFit-project/virtual-coach-issues/assets/118284434/8d68c226-f47e-4f6d-a17b-2cf51c64e252)

EHBO command: after Welke oefening wil je zien? I think the coach should say something like "Typ het getal dat voor de oefening staat." and not only after someone has responded incorrectly 

I think that if we have cross references between exercises we should mention the category that another exercise is in
Addition Anke: I think we already added this. 

General activity dialog: Bedankt om dat te delen should be Bedankt voor het delen 

I think there should also be an option to opt out of the general activity dialog, like we now also have for the hrs dialog. I typed "wat een rare oefeningen" and then I was in the general activity dialog again. This option could be added to the message that schedules the exercise: Typ '3' als je per ongeluk oefening hebt getypt en geen oefening wilt doen.

**Comment by nelealbers** [comment]
I already removed the three dots in the persuasive messages in https://github.com/PerfectFit-project/virtual-coach-db/pull/76.

**Comment by wbaccinelli** [comment]
> I set August 4th as my quit date but on that they I did not get a specific message indicating that it was my quit date (not sure whether this was programmed but would be good to send something), instead I immediately got the weekly reflection dialog and had to indicate how much I had smoked last week, which should be quite some cigarettes as I would have had only 1 day without smoking
Additions Anke: I got a video about 'uitleg coachingsfase', but I agree that a message saying today is your quit day would be very beneficial'.

@aversluis1 The notification about the quitting date has been designed just in case the date changes (so, after a relapse). It is possible to add a notification also in this case, but I would strongly suggest to not add new logics now.

> I think there should also be an option to opt out of the general activity dialog, like we now also have for the hrs dialog. I typed "wat een rare oefeningen" and then I was in the general activity dialog again. This option could be added to the message that schedules the exercise: Typ '3' als je per ongeluk oefening hebt getypt en geen oefening wilt doen.

The same goes for the possibility to exit the general activity. This is also a dialog that is triggered sometimes by the VC, so changing and adapting the questions would be very very difficult. We should not go in that direction.

> 4/8 I said dankjewel after the weekly reflection and then the hrs dialog started as I had apparently used my code word, see screenshot
> 4/8 19.50 I texted some nonsense and got Sorry er is nu geen onvoltooide dialoog om af te maken, with the menu. Is that intended?

I think that the intent recognition issue has been reported multiple times. All [here](https://github.com/PerfectFit-project/virtual-coach-issues/issues/404)

> 19.59 the coach stopped during the general activity dialog. I was on the campsite but I think my internet connection was ok. See screenshot

The screenshot shows something different, I think.

**Comment by aversluis1** [comment]
@wbaccinelli, regarding the quitting date message and the general activity dialog exit - I understand to not focus on this, if this takes a lot of time. We could maybe put it on a waitlist in case there is time? (Which I realise there is probably isn't)

Intent recognition we have indeed notified more often, and happens quite frequently when using the app. 

Screenshot was indeed different - it was related to the previous item (intent recognition). Although Eline refers to a screenshot, I don't think there actually was one.
