### ISSUE TITLE
weekly reflection - timing

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#422]
Tester Eline

1. After finishing the exercise the weekly reflection dialog continued but I had also done that yesterday (on my quit day), see screenshot 

![Screenshot_20230805-121011](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/d01c2305-bdf1-486d-86c5-693cc18a485f)

2. Weekly reflection, difficult situations for urge to smoke when someone hasn't smoked: options for how you felt range from 1-9 but it seems that you can only enter one value, otherwise it says that you can only enter a number between 1 and 7. See screenshot 
![Screenshot_20230805-121628](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/5430c8ec-777f-48d5-b834-831680c78446)

3. Later it says "Was er een specifieke reden waarom je op dat moment rookte?" but this should be "Was er een specifieke reden waarom je op dat moment trek had om te roken?" as I indicated before that I hadn't smoked 

4. I think I was supposed to see a picture with high risk situations for PA but there was no picture, see screenshot  
![Screenshot_20230805-122343](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/5677e6ce-b3f4-4a50-9b83-9e415a941a0b)

**Comment by wbaccinelli** [comment]
first point already solved [here](https://github.com/PerfectFit-project/virtual-coach-rasa/pull/142)

**Comment by wbaccinelli** [comment]
@aversluis1 for point 3, there is also this formulation that needs to be changed, I think: 'Was er een aanleiding voor het roken, of was het spontaan?'. What should I use instead?

**Comment by aversluis1** [comment]
@wbaccinelli , maybe "Hoe kwam het dat je trek had om te roken, of kwam het spontaan?"
