### ISSUE TITLE
goal setting: two of the same messages shown

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#432]
tester eline

8/8 12.00 I got the messages on the weekly PA goal, but I received two variations of each message. See screenshots

![Screenshot_20230808-201324](https://github.com/PerfectFit-project/virtual-coach-issues/assets/118284434/f2c1ed10-afdf-4f2c-82b9-cf324f29d298)

![Screenshot_20230808-201333](https://github.com/PerfectFit-project/virtual-coach-issues/assets/118284434/76acc8cf-cb9e-4178-9f82-c098c6380486)

**Comment by wbaccinelli** [comment]
Double scheduling of the notification corrected [here](https://github.com/PerfectFit-project/virtual-coach-rasa/pull/142)
