### ISSUE TITLE
Problems with 'verder' 

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#437]
The tester who experienced problems with conintuing the dialog (Josine Schaap), still expriences problems (she was on holiday past two weeks). 

She typed verder, and it worked - but after typing 1 - no response followed. 
![Niceday](https://github.com/PerfectFit-project/virtual-coach-issues/assets/118284434/89752115-3ebb-46b8-aeb7-dfef461b0350)

**Comment by emeijerperfectfit** [comment]
Yesterday the closing dialog started, but I did not do it immediately. however I was unable to continue by using the verder command. See below!
account e.meijer@lumc.nl

![Screenshot_20230911-160444](https://github.com/PerfectFit-project/virtual-coach-issues/assets/135458606/94150f21-1e1d-4325-985c-3cca9e4e0176)

**Comment by wbaccinelli** [comment]
Yes, this was actually a bug. solved [here](https://github.com/PerfectFit-project/virtual-coach-rasa/pull/185)
