### ISSUE TITLE
Mindfulness video

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#440]
-	I could not click on the YouTube link of the mindfulness video or the link to YouTube in general (other links did work).
- tester: Roxy

**Comment by wbaccinelli** [comment]
Just checked. For some reason YouTube links don't work in the NiceDay app. I am going to report this to NiceDay. If they don't solve this on time, we should review the links somehow

**Comment by wbaccinelli** [comment]
Quickfix: the links will work with capitalized "y"

**Comment by aversluis1** [comment]
Great that there is an easy fix!
