### ISSUE TITLE
Chat messages do not appear

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#441]
-	After watching a video and returning to the app (by pressing back button on my phone), sometimes messages would not load. On two separate occasions, my phone received new messages, but they did not appear in the chat. Only after closing the app completely and restarting, the new messages appeared in the chat. 
- Tester: Roxy

**Comment by wbaccinelli** [comment]
Synch problem, already reported to NiceDay. Should be solved in few weeks. See [here](https://github.com/PerfectFit-project/testing-tickets/issues/52#issuecomment-1672655804).
