### ISSUE TITLE
nightly notifications / uncorrect 'code word' 

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#443]
Tester: Janita Meijer

Tester has downloaded the app, but doesnt use it. 
She just got the message she has used a code word to ask for help, even though she didn't. 
Also she continuously gets messages in the night.

**Comment by wbaccinelli** [comment]
- I see that some times ago she started (by mistake) the help dialog, so the dialog keeps on being resent. The misleading initial sentence has been corrected [here](https://github.com/PerfectFit-project/virtual-coach-rasa/pull/156), the possibility of running the hrs dialog in the preparation phase has been removed [here](https://github.com/PerfectFit-project/virtual-coach-rasa/pull/136)
- I also see that no messages have been sent after 22 recently, as the issue has been fixed [here](https://github.com/PerfectFit-project/virtual-coach-rasa/pull/141)
