### ISSUE TITLE
Time mentioned in goal-setting dialog does not match actual number of days

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/virtual-coach-server#453]
See here: https://github.com/PerfectFit-project/testing-tickets/issues/69.

**Comment by bscheltinga** [comment]
I think this is an effect of artificially shortening the preperation phase for testing purposes. So not really a bug here.

**Comment by nelealbers** [comment]
> I think this is an effect of artificially shortening the preperation phase for testing purposes. So not really a bug here.

@bscheltinga Ah I see, that would make sense. Maybe @wbaccinelli can confirm just to be safe.

**Comment by wbaccinelli** [comment]
Yes, you are right @nelealbers @bscheltinga, indeed the shortened version of the intervention does not have 9 days of tracking, but the sentence is hardcoded.
