### ISSUE TITLE
General activity dialog with 'Kies jouw sport of beweging' activity during preparation phase

### ISSUE THREAD

**Issue by Milonvv** [PerfectFit-project/virtual-coach-server#459]
According to the timing in the Perfect Fit bible intervention overview, the general activity dialog with the activity 'Kies jouw sport of beweging' should be triggered before the goal-setting dialog. However, I did not receive this activity dialog during the preparation phase (the coach started with the goal-setting dialog, immediately after the dialog about the future-self video). 

Is there something going wrong or did you choose not to implement this activity dialog about 'Kies jouw sport of beweging' after all?

**Comment by nelealbers** [comment]
@Milonvv I just checked our database [here](https://github.com/PerfectFit-project/virtual-coach-db/blob/main/resources/resources_timing.json). Supposedly the activity 'kies jouw sport of beweging' is mandatory on day 7 of the tracking phase. I am not sure what happens when people have a shorter tracking phase (as you do now for the testing I suppose).
But maybe @wbaccinelli knows more once he is back from vacation.

**Comment by Milonvv** [comment]
@nelealbers Thanks for checking. Let's see what @wbaccinelli thinks about it indeed. 

I see that the original plan in the bible was to make the activity 'Kies jouw sport of beweging' mandatory at day 7 of the preparation phase, the activity 'doe het anders' on week 1 of the execution phase (around quit date), and the educational activity 'Veranderingen in je lichaam' on week 2 of the execution phase. I will check if I do get these activities in week 1 and 2 of the execution phase. It could also be that this plan changed or it was too difficult to implement or something. Let's wait for Walter's answer indeed.

**Comment by wbaccinelli** [comment]
@Milonvv @nelealbers the activity should actually start automatically on day 7 of the preparation phase. I just checked the code and I spotted the problem. The preparation in the testing has been shortened so much that the activity should be triggered on day 2, but we are running into an edge case where the dialog is skipped. I will try to make the logic more robust
