### ISSUE TITLE
Weekly reflection dialog - Smartwatch data not correctly shown

### ISSUE THREAD

**Issue by Milonvv** [PerfectFit-project/virtual-coach-server#460]
When I went through the weekly reflection dialog, the wrong image appeared when the amount of steps and my personal stepgoal of the previous week should have been shown (see image below). Also, instead of showing the number of days that I achieved my stepgoal, it showed the word 'None' ("Je hebt op None dagen je stappendoel (bijna) gehaald.")

@bscheltinga Already knows about this bug
![WhatsApp Image 2023-08-31 at 12 43 55](https://github.com/PerfectFit-project/testing-tickets/assets/91131769/d56f0f27-8aaa-495c-9e8e-1d074a9fca28)

**Comment by wbaccinelli** [comment]
@bscheltinga I see the following error from the actions, maybe you can take a look?
![image](https://github.com/PerfectFit-project/virtual-coach-issues/assets/100706999/771dba3a-1f6b-40ee-b8b9-8cc217cddfd2)

**Comment by wbaccinelli** [comment]
Fixed [here](https://github.com/PerfectFit-project/virtual-coach-rasa/pull/181
