### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by aversluis1** [PerfectFit-project/virtual-coach-server#468]
I am in week 6 of the coaching/intervention, and tried to use the 'help' command - however, i keep getting the message that i am in the preparation phase and can only use it when I reach the coaching phase. But I believe I am already there... 

![image](https://github.com/PerfectFit-project/testing-tickets/assets/118284434/1d5ccb04-ba41-4396-a43a-687ca22d5dae)

**Comment by wbaccinelli** [comment]
@aversluis1 I see that you are already in the closing phase, this is why you cannot use the the relapse dialog. The phrasing is indeed very misleading

**Comment by aversluis1** [comment]
@wbaccinelli, can we still change the phrasing? Or is it too late / difficult?

**Comment by wbaccinelli** [comment]
@aversluis1 it is possible. It would be great to have a more general sentence that does not mention the preparation phase.

**Comment by aversluis1** [comment]
Great - Then I would say " Je bent nu niet in de uitvoeringsfase. Je kunt help alleen gebruiken in deze fase.'

**Comment by nelealbers** [comment]
@wbaccinelli I had a look at the [domain](https://github.com/PerfectFit-project/virtual-coach-rasa/blob/main/Rasa_Bot/domain/domain_common.yml) and I saw that we have this notification for both the help and the ehbo command. Are both of these only available in the uitvoeringsfase (i.e., not in the closing phase)? Then I would change both of them.

**Comment by wbaccinelli** [comment]
@nelealbers No, the availability of the commands is different. The 'ehbo' command is should be always available from the moment the first aid kit video has been shown, while the help is available only during the execution (not during the preparation, the closing and the relapse).

**Comment by nelealbers** [comment]
@wbaccinelli Okay, then I will only change the message for the help command!
