### ISSUE TITLE
Make "doel"-command unavailable when it is not to be used

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/virtual-coach-server#473]
Before the goal-setting dialog, the "doel"-command currently still works (ie.., people will get a goal also then), but this would be confusing. So when people type "doel" before the goal-setting dialog, there should be a message that this command is not yet available. We have implemented something similar for the help-command.

If this is merged into the intervention after 1/10/2023, contact Milon with the merging time so she can keep track.

**Comment by bscheltinga** [comment]
@wbaccinelli do we still want this issue? Or do we see it nog as a 'bug' but as a feature, as this functionality can be used as a check if the sensor data comes in?

**Comment by wbaccinelli** [comment]
Let's close this one
