### ISSUE TITLE
General activity uncompleted before goal setting dialog

### ISSUE THREAD

**Issue by wbaccinelli** [PerfectFit-project/virtual-coach-server#481]
Some users didn't get the possibility to resume the goal setting dialog because some general activity dialogs were pending (uncompleted in the DB).  From a quick check, this can be caused by [this](https://github.com/PerfectFit-project/virtual-coach-rasa/blob/e77f66a706690f3990e541b5181ab78010765670/scheduler/state_machine/controller.py#L238). As activity 2.9 has to be proposed on day 7, during the tracking phase the coach checks every new day if the activity has been completed and, if not, it sends the dialog to the user. But if the goal setting dialog is also due, it will move to the next phase and start the dialog with [this check](https://github.com/PerfectFit-project/virtual-coach-rasa/blob/e77f66a706690f3990e541b5181ab78010765670/scheduler/state_machine/controller.py#L250). 
This  results in many uncompleted general activity dialogs in case the user doesn't complete it on time, and in the delivery of the dialogs at the same time.

- [ ] change order of events (first check if is time to run the goals setting, then the general activity check)
- [ ] avoid creating new general activity dialogs entries in the DB if an uncompleted dialog is already in the DB
- [ ] verify the the 'verder' command triggers the latest dialog proposed

**Comment by wbaccinelli** [comment]
@BendikC this is the reference issue, in case you get to work on this before me

**Comment by BendikC** [comment]
After discussion, this issue is now changed to this:
- [x] Alter the plan_and_store such that we first check if there is an uncompleted general activity dialog, and trigger it
- [x] Change the verder logic sucht that it does not resume a general activity dialog, if there are other uncompleted dialogs to be run.
