### ISSUE TITLE
Rasa Version

### ISSUE THREAD

**Issue by nelealbers** [PerfectFit-project/virtual-coach-server#55]
Currently, the language model of the Rasa agent is trained in Rasa 2.0.2. Different Rasa versions are not necessarily compatible w.r.t. e.g. layout of the language model files, so we should eventually choose a specific Rasa version, probably the most current one (2.6.0 at the time of this writing). See [here](https://rasa.com/docs/rasa/changelog) for the changelog for Rasa Open Source.

- [x] Decide on a Rasa version to use.
- [x] Adapt existing Rasa code, Dockerfile etc. based on that chosen version.
- [x] Retrain the language model.
- [x] Update custom action Docker image if needed.

**Comment by svenvanderburg** [comment]
Indeed the most current one seems the right choice!
