### ISSUE TITLE
Request training schema from mock algorithm

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#6]
- [x] Setup mock algorithm that returns a weekly training schema given age of user (more features to be added later) (for example: 100 - age number of push-ups.
- [x] Set it up in a separate repository python library that will serve as an example/tryout on the interface between an algorithm and the rest of the system
- [x] We can install and call the algorithm library in this repo

**Comment by svenvanderburg** [comment]
@bscheltinga I think this would be an interesting task for you during the sprint (if you have the time of course). Feel free to refine the description!

**Comment by bscheltinga** [comment]
@svenvanderburg I think it's a good idea. It will be a nice exercise to get familiar with the whole project organization.

**Comment by bscheltinga** [comment]
@svenvanderburg I pushed the library to [https://github.com/PerfectFit-project/pa-algorithms](https://github.com/PerfectFit-project/pa-algorithms).

**Comment by svenvanderburg** [comment]
Cool! 
* I have reviewed your changes in this [PR](https://github.com/PerfectFit-project/pa-algorithms/pull/2). It looks nice! NB: Now you did all your changes in the 'main' branch, next time you should do your changes in a new branch, and then submit a Pull Request, and if the reviewer approves we merge the changes. I now created this PR based on a branch pointing to your initial commit.
* Can you update https://github.com/PerfectFit-project/virtual-coach-server/blob/main/Rasa_Bot/actions/actions.py#L31 so that we use the `paalgorithms` library to get the number of kilometers to run? This means you'll need to learn a little bit about Rasa, you can follow [this tutorial](https://towardsdatascience.com/chatbots-made-easier-with-rasa-2-0-b999323cdde). Again create a new branch and submit a PR wit your changes.
* Please don't hesitate to contact me with questions!
