### ISSUE TITLE
Implement GET niceday user profile

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#61]
* [x] Update the niceday-api so it has an endpoint for requesting the user profile
* [x] This is the first method that we need to call from a python application, so create a nice python client for it: Create a new module in the Rasa_Bot folder in it create a client python class `NicedayClient` for communicating with the niceday api.
* [x] Add a method `NicedayClient.get_profile()` for getting the profile.
Checkout documentation of https://github.com/senseobservationsystems/goalie-js

This blocks #62

**Comment by raar1** [comment]
API endpoint added, but currently only able to fetch the therapist's own profile, not any of the (existing) clients. Most likely we have misunderstood something. Asked for help [here] (https://github.com/senseobservationsystems/goalie-js/issues/818).
