### ISSUE TITLE
Add first test for niceday-api

### ISSUE THREAD

**Issue by svenvanderburg** [PerfectFit-project/virtual-coach-server#69]
See temporary mock test here: https://github.com/PerfectFit-project/virtual-coach-server/blob/ab1cd8da651508bc9c3af24327a9814b1a765d4c/niceday-api/index.test.js#L1

We should replace it with a test that actually tests functionality.

AB#2022

**Comment by raar1** [comment]
Are we talking about unit tests here (which would probably test very little in this case)?  Or use the real (or mocked) sense server?

**Comment by raar1** [comment]
I'm going with mocked server, so stop me if that's wrong ;)
