### ISSUE TITLE
Update RASA ActionSetReminder with daily reminder

### ISSUE THREAD

**Issue by CunliangGeng** [PerfectFit-project/virtual-coach-server#97]
This issue is created from PR #89 .

- [ ] check file `Rasa_bot/actions/action.py` and update the class `ActionSetReminder` to use daily reminder for production

AB#2036

**Comment by svenvanderburg** [comment]
This has changed in the meantime, so I am closing the ticket.

**Comment by svenvanderburg** [comment]
The actual specifics of triggered events will be the outcome of content development anyways.
